import React, { useState } from 'react';

const Form = ({ onSubmit }) => {
  const [gradeLevel, setGradeLevel] = useState('');
  const [subject, setSubject] = useState('');
  const [knowledge, setKnowledge] = useState('');
  const [skill, setSkill] = useState('');

  //structure form data so that innermost children are passed up through the select options (start with skill options)ß

  const subjectOptions = {
    // Elementary: ['Math', 'Science', 'English'],
    // 'Middle School': ['Math', 'Science', 'English', 'History'],
    'High School': ['High School Science'],
  };

  const knowledgeOptions = {
    'High School Science': ['Aquatic Science', 'Biology', 'Chemistry', 'IPC'],
  };

  const skillOptions = {
    'Chemistry': [
        "(1A) ask questions and define problems based on observations or information from text, phenomena, models, or investigations;","(1B) apply scientific practices to plan and conduct descriptive, comparative, and experimental investigations and use engineering practices to design solutions to problems;","(1C) use appropriate safety equipment and practices during laboratory, classroom, and field investigations as outlined in Texas Education Agency-approved safety standards;","(1D) use appropriate tools such as Safety Data Sheets (SDS), scientific or graphing calculators, computers and probes, electronic balances, an adequate supply of consumable chemicals, and sufficient scientific glassware such as beakers, Erlenmeyer flasks, pipettes, graduated cylinders, volumetric flasks, and burettes;","(1E) collect quantitative data using the International System of Units (SI) and qualitative data as evidence;","(1F) organize quantitative and qualitative data using oral or written lab reports, labeled drawings, particle diagrams, charts, tables, graphs, journals, summaries, or technology-based reports;","(1G) develop and use models to represent phenomena, systems, processes, or solutions to engineering problems; and","(1H) distinguish between scientific hypotheses, theories, and laws.",
        "(2A) identify advantages and limitations of models such as their size, scale, properties, and materials;","(2B) analyze data by identifying significant statistical features, patterns, sources of error, and limitations;","(2C) use mathematical calculations to assess quantitative relationships in data; and","(2D) evaluate experimental and engineering designs.",
        "(3A) develop explanations and propose solutions supported by data and models and consistent with scientific ideas, principles, and theories;","(3B) communicate explanations and solutions individually and collaboratively in a variety of settings and formats; and","(3C) engage respectfully in scientific argumentation using applied scientific explanations and empirical evidence.",
        "(4A) analyze, evaluate, and critique scientific explanations and solutions by using empirical evidence, logical reasoning, and experimental and observational testing, so as to encourage critical thinking by the student;", "(4B) relate the impact of past and current research on scientific thought and society, including research methodology, cost-benefit analysis, and contributions of diverse scientists as related to the content; and",  "(4C) research and explore resources such as museums, libraries, professional organizations, private companies, online platforms, and mentors employed in a science, technology, engineering, and mathematics (STEM) field in order to investigate STEM careers.",  
        "(5A) explain the development of the Periodic Table over time using evidence such as chemical and physical properties;",  "(5B) predict the properties of elements in chemical families, including alkali metals, alkaline earth metals, halogens, noble gases, and transition metals, based on valence electrons patterns using the Periodic Table; and",  "(5C) analyze and interpret elemental data, including atomic radius, atomic mass, electronegativity, ionization energy, and reactivity to identify periodic trends.", 
        "(6A) construct models using Dalton's Postulates, Thomson's discovery of electron properties, Rutherford's nuclear atom, Bohr's nuclear atom, and Heisenberg's Uncertainty Principle to show the development of modern atomic theory over time;",  "(6B) describe the structure of atoms and ions, including the masses, electrical charges, and locations of protons and neutrons in the nucleus and electrons in the electron cloud;",  "(6C) investigate the mathematical relationship between energy, frequency, and wavelength of light using the electromagnetic spectrum and relate it to the quantization of energy in the emission spectrum;",  "(6D) calculate average atomic mass of an element using isotopic composition; and",  "(6E) construct models to express the arrangement of electrons in atoms of representative elements using electron configurations and Lewis dot structures.",  
        "(7A) construct an argument to support how periodic trends such as electronegativity can predict bonding between elements;",  "(7B) name and write the chemical formulas for ionic and covalent compounds using International Union of Pure and Applied Chemistry (IUPAC) nomenclature rules;",  "(7C) classify and draw electron dot structures for molecules with linear, bent, trigonal planar, trigonal pyramidal, and tetrahedral molecular geometries as explained by Valence Shell Electron Pair Repulsion (VSEPR) theory; and",  "(7D) analyze the properties of ionic, covalent, and metallic substances in terms of intramolecular and intermolecular forces.",  
        "(8A) define mole and apply the concept of molar mass to convert between moles and grams;",  "(8B) calculate the number of atoms or molecules in a sample of material using Avogadro's number;",  "(8C) calculate percent composition of compounds; and",  "(8D) differentiate between empirical and molecular formulas.",
        "(9A) interpret, write, and balance chemical equations, including synthesis, decomposition, single replacement, double replacement, and combustion reactions using the law of conservation of mass;",  "(9B) differentiate among acid-base reactions, precipitation reactions, and oxidation-reduction reactions;",  "(9C) perform stoichiometric calculations, including determination of mass relationships, gas volume relationships, and percent yield; and",  "(9D) describe the concept of limiting reactants in a balanced chemical equation.",  
        "(10A) describe the postulates of the kinetic molecular theory;",  "(10B) describe and calculate the relationships among volume, pressure, number of moles, and temperature for an ideal gas; and",  "(10C) define and apply Dalton's law of partial pressure.",  
        "(11A) describe the unique role of water in solutions in terms of polarity;",  "(11B) distinguish among types of solutions, including electrolytes and nonelectrolytes and unsaturated, saturated, and supersaturated solutions;",  "(11C) investigate how solid and gas solubilities are influenced by temperature using solubility curves and how rates of dissolution are influenced by temperature, agitation, and surface area;",  "(11D) investigate the general rules regarding solubility and predict the solubility of the products of a double replacement reaction;",  "(11E) calculate the concentration of solutions in units of molarity; and",  "(11F) calculate the dilutions of solutions using molarity.",
        "(12A) name and write the chemical formulas for acids and bases using IUPAC nomenclature rules;","(12B) define acids and bases and distinguish between Arrhenius and Bronsted-Lowry definitions;","(12C) differentiate between strong and weak acids and bases;","(12D) predict products in acid-base reactions that form water; and","(12E) define pH and calculate the pH of a solution using the hydrogen ion concentration.",
        "(13A) explain everyday examples that illustrate the four laws of thermodynamics;","(13B) investigate the process of heat transfer using calorimetry;","(13C) classify processes as exothermic or endothermic and represent energy changes that occur in chemical reactions using thermochemical equations or graphical analysis; and","(13D) perform calculations involving heat, mass, temperature change, and specific heat.",
        "(14A) describe the characteristics of alpha, beta, and gamma radioactive decay processes in terms of balanced nuclear equations;","(14B) compare fission and fusion reactions; and","(14C) give examples of applications of nuclear phenomena such as nuclear stability, radiation therapy, diagnostic imaging, solar cells, and nuclear power."
    
    ],
    'Aquatic Science': [
        "(A1) ask questions and define problems based on observations or information from text, phenomena, models, or investigations;","(B1) apply scientific practices to plan and conduct descriptive, comparative, and experimental investigations and use engineering practices to design solutions to problems;","(C1) use appropriate safety equipment and practices during laboratory, classroom, and field investigations as outlined in Texas Education Agency-approved safety standards;","(D1) use appropriate tools such as Global Positioning System (GPS), Geographic Information System (GIS), weather balloons, etc.;","(E1) collect quantitative data using the International System of Units (SI) and qualitative data as evidence;","(F1) organize quantitative and qualitative data using probeware, spreadsheets, lab notebooks or journals, models, diagrams, graphs paper, computers, or cellphone applications;","(G1) develop and use models to represent phenomena, systems, processes, or solutions to engineering problems; and","(H1) distinguish between scientific hypotheses, theories, and laws.","(2A) identify advantages and limitations of models such as their size, scale, properties, and materials;",
        "(2B) analyze data by identifying significant statistical features, patterns, sources of error, and limitations;","(2C) use mathematical calculations to assess quantitative relationships in data; and","(2D) evaluate experimental and engineering designs.",
        "(3A) develop explanations and propose solutions supported by data and models consistent with scientific ideas, principles, and theories;","(3B) communicate explanations and solutions individually and collaboratively in a variety of settings and formats; and","(3C) engage respectfully in scientific argumentation using applied scientific explanations and empirical evidence.",
        "(4A) analyze, evaluate, and critique scientific explanations and solutions by using empirical evidence, logical reasoning, and experimental and observational testing, so as to encourage critical thinking by the student;","(4B) relate the impact of past and current research on scientific thought and society, including research methodology, cost-benefit analysis, and contributions of diverse scientists as related to the content; and","(4C) research and explore resources such as museums, planetariums, observatories, libraries, professional organizations, private companies, online platforms, and mentors employed in a science, technology, engineering, and mathematics (STEM) field in order to investigate STEM careers.",
        "(5A) describe how the shape and polarity of the water molecule make it a 'universal solvent' in aquatic systems;","(5B) identify how aquatic ecosystems are affected by water's properties of adhesion, cohesion, surface tension, heat capacity, and thermal conductivity; and","(5C) explain how the density of water is critical for organisms in cold environments.","(6A) identify key features and characteristics of atmospheric, geological, hydrological, and biological systems as they relate to aquatic environments;",
        "(6B) describe the interrelatedness of atmospheric, geological, hydrological, and biological systems in aquatic ecosystems, including positive and negative feedback loops; and","(6C) evaluate environmental data using technology such as maps, visualizations, satellite data, Global Positioning System (GPS), Geographic Information System (GIS), weather balloons, and buoys to model the interactions that affect aquatic ecosystems.",
        "(7A) identify how energy flows and matter cycles through both freshwater and marine aquatic systems, including food webs, chains, and pyramids;","(7B) identify biological, chemical, geological, and physical components of an aquatic life zone as they relate to the organisms in it;","(7C) identify variables that affect the solubility of carbon dioxide and oxygen in water;","(7D) evaluate factors affecting aquatic population cycles such as lunar cycles, temperature variations, hours of daylight, and predator-prey relationships; and","(7E) identify the interdependence of organisms in an aquatic environment such as in a pond, a river, a lake, an ocean, or an aquifer and the biosphere.",
        "(8A) evaluate data over a period of time from an established aquatic environment documenting seasonal changes and the behavior of organisms;","(8B) collect and analyze pH, salinity, temperature, mineral content, nitrogen compounds, dissolved oxygen, and turbidity data periodically, starting with baseline measurements; and","(8C) use data from short-term or long-term studies to analyze interrelationships between producers, consumers, and decomposers in aquatic ecosystems.",
        "(9A) identify the role of carbon, nitrogen, water, and nutrient cycles in an aquatic environment, including upwellings and turnovers;",
        "(9B) examine the interrelationships between aquatic systems and climate and weather, including El Niño and La Niña, currents, and hurricanes; and","(9C) explain how tidal cycles influence intertidal ecology.",
        "(10A) identify sources of water in a watershed, including rainfall, groundwater, and surface water;","(10B) identify factors that contribute to how water flows through a watershed;","(10C) analyze water quantity and quality in a local watershed or aquifer; and","(10D) describe human uses of fresh water and how human freshwater use competes with that of other organisms.",
        "(11A) examine basic principles of fluid dynamics, including hydrostatic pressure, density as a result of salinity, and buoyancy;"
     ],
    'Biology': [
        "(1A) ask questions and define problems based on observations or information from text, phenomena, models, or investigations;","(1B) apply scientific practices to plan and conduct descriptive, comparative, and experimental investigations and use engineering practices to design solutions to problems;","(1C) use appropriate safety equipment and practices during laboratory, classroom, and field investigations as outlined in Texas Education Agency-approved safety standards;","(1D) use appropriate tools such as microscopes, slides, Petri dishes, laboratory glassware, metric rulers, digital balances, pipets, filter paper, micropipettes, gel electrophoresis and polymerase chain reaction (PCR) apparatuses, microcentrifuges, water baths, incubators, thermometers, hot plates, data collection probes, test tube holders, lab notebooks or journals, hand lenses, and models, diagrams, or samples of biological specimens or structures;","(1E) collect quantitative data using the International System of Units (SI) and qualitative data as evidence;","(1F) organize quantitative and qualitative data using scatter plots, line graphs, bar graphs, charts, data tables, digital tools, diagrams, scientific drawings, and student-prepared models;","(1G) develop and use models to represent phenomena, systems, processes, or solutions to engineering problems; and","(1H) distinguish among scientific hypotheses, theories, and laws.",
        "(2A) identify advantages and limitations of models such as their size, scale, properties, and materials;","(2B) analyze data by identifying significant statistical features, patterns, sources of error, and limitations;","(2C) use mathematical calculations to assess quantitative relationships in data; and","(2D) evaluate experimental and engineering designs.",
        "(3A) develop explanations and propose solutions supported by data and models and consistent with scientific ideas, principles, and theories;","(3B) communicate explanations and solutions individually and collaboratively in a variety of settings and formats; and","(3C) engage respectfully in scientific argumentation using applied scientific explanations and empirical evidence.",
        "(4A) analyze, evaluate, and critique scientific explanations and solutions by using empirical evidence, logical reasoning, and experimental and observational testing, so as to encourage critical thinking by the student;",
        "(4B) relate the impact of past and current research on scientific thought and society, including research methodology, cost-benefit analysis, and contributions of diverse scientists as related to the content; and",
        "(4C) research and explore resources such as museums, libraries, professional organizations, private companies, online platforms, and mentors employed in a science, technology, engineering, and mathematics (STEM) field in order to investigate STEM careers.",
        "(5A) relate the functions of different types of biomolecules, including carbohydrates, lipids, proteins, and nucleic acids, to the structure and function of a cell;","(5B) compare and contrast prokaryotic and eukaryotic cells, including their complexity, and compare and contrast scientific explanations for cellular complexity;","(5C) investigate homeostasis through the cellular transport of molecules; and","(5D) compare the structures of viruses to cells and explain how viruses spread and cause disease.",
        "(6A) explain the importance of the cell cycle to the growth of organisms, including an overview of the stages of the cell cycle and deoxyribonucleic acid (DNA) replication models;","(6B) explain the process of cell specialization through cell differentiation, including the role of environmental factors; and","(6C) relate disruptions of the cell cycle to how they lead to the development of diseases such as cancer.",
        "(7A) identify components of DNA, explain how the nucleotide sequence specifies some traits of an organism, and examine scientific explanations for the origin of DNA;","(7B) describe the significance of gene expression and explain the process of protein synthesis using models of DNA and ribonucleic acid (RNA);","(7C) identify and illustrate changes in DNA and evaluate the significance of these changes; and","(7D) discuss the importance of molecular technologies such as polymerase chain reaction (PCR), gel electrophoresis, and genetic engineering that are applicable in current research and engineering practices.",
        "(8A) analyze the significance of chromosome reduction, independent assortment, and crossing-over during meiosis in increasing diversity in populations of organisms that reproduce sexually; and","(8B) predict possible outcomes of various genetic combinations using monohybrid and dihybrid crosses, including non-Mendelian traits of incomplete dominance, codominance, sex-linked traits, and multiple alleles.",
        "(9A) analyze and evaluate how evidence of common ancestry among groups is provided by the fossil record, biogeography, and homologies, including anatomical, molecular, and developmental; and","(9B) examine scientific explanations for varying rates of change such as gradualism, abrupt appearance, and stasis in the fossil record.",
        "(10A) analyze and evaluate how natural selection produces change in populations and not in individuals;","(10B) analyze and evaluate how the elements of natural selection, including inherited variation, the potential of a population to produce more offspring than can survive, and a finite supply of environmental resources, result in differential reproductive success;","(10C) analyze and evaluate how natural selection may lead to speciation; and","(10D) analyze evolutionary mechanisms other than natural selection, including genetic drift, gene flow, mutation, and genetic recombination, and their effect on the gene pool of a population.",
        "(11A) explain how matter is conserved and energy is transferred during photosynthesis and cellular respiration using models, including the chemical equations for these processes; and","(11B) investigate and explain the role of enzymes in facilitating cellular processes.",
        "(12A) analyze the interactions that occur among systems that perform the functions of regulation, nutrient absorption, reproduction, and defense from injury or illness in animals;","(12B) explain how the interactions that occur among systems that perform functions of transport, reproduction, and response in plants are facilitated by their structures.",
        "(13A) investigate and evaluate how ecological relationships, including predation, parasitism, commensalism, mutualism, and competition, influence ecosystem stability;","(13B) analyze how ecosystem stability is affected by disruptions to the cycling of matter and flow of energy through trophic levels using models;","(13C) explain the significance of the carbon and nitrogen cycles to ecosystem stability and analyze the consequences of disrupting these cycles; and","(13D) explain how environmental change, including change due to human activity, affects biodiversity and analyze how changes in biodiversity impact ecosystem stability.",
    ],
    'IPC': [
        "(1A) ask questions and define problems based on observations or information from text, phenomena, models, or investigations;","(1B) apply scientific practices to plan and conduct descriptive, comparative, and experimental investigations and use engineering practices to design solutions to problems;","(1C) use appropriate safety equipment and practices during laboratory, classroom, and field investigations as outlined in Texas Education Agency-approved safety standards;","(1D) use appropriate tools such as data-collecting probes, software applications, the internet, standard laboratory glassware, metric rulers, meter sticks, spring scales, multimeters, Gauss meters, wires, batteries, light bulbs, switches, magnets, electronic balances, mass sets, Celsius thermometers, hot plates, an adequate supply of consumable chemicals, lab notebooks or journals, timing devices, models, and diagrams;","(1E) collect quantitative data using the International System of Units (SI) and qualitative data as evidence;","(1F) organize quantitative and qualitative data using labeled drawings and diagrams, graphic organizers, charts, tables, and graphs;","(1G) develop and use models to represent phenomena, systems, processes, or solutions to engineering problems; and","(1H) distinguish between scientific hypotheses, theories, and laws.",
        "(2A) identify advantages and limitations of models such as their size, scale, properties, and materials;","(2B) analyze data by identifying significant statistical features, patterns, sources of error, and limitations;","(2C) use mathematical calculations to assess quantitative relationships in data; and","(2D) evaluate experimental and engineering designs.",
        "(3A) develop explanations and propose solutions supported by data and models and consistent with scientific ideas, principles, and theories;","(3B) communicate explanations and solutions individually and collaboratively in a variety of settings and formats; and","(3C) engage respectfully in scientific argumentation using applied scientific explanations and empirical evidence.",
        "(4A) analyze, evaluate, and critique scientific explanations and solutions by using empirical evidence, logical reasoning, and experimental and observational testing, so as to encourage critical thinking by the student;","(4B) relate the impact of past and current research on scientific thought and society, including research methodology, cost-benefit analysis, and contributions of diverse scientists as related to the content; and","(4C) research and explore resources such as museums, libraries, professional organizations, private companies, online platforms, and mentors employed in a science, technology, engineering, and mathematics (STEM) field in order to investigate STEM careers.",
        "(5A) investigate, analyze, and model motion in terms of position, velocity, acceleration, and time using tables, graphs, and mathematical relationships;","(5B) analyze data to explain the relationship between mass and acceleration in terms of the net force on an object in one dimension using force diagrams, tables, and graphs;","(5C) apply the concepts of momentum and impulse to design, evaluate, and refine a device to minimize the net force on objects during collisions such as those that occur during vehicular accidents, sports activities, or the dropping of personal electronic devices;","(5D) describe the nature of the four fundamental forces: gravitation; electromagnetic; the strong and weak nuclear forces, including fission and fusion; and mass-energy equivalency;","(5E) construct and communicate an explanation based on evidence for how changes in mass, charge, and distance affect the strength of gravitational and electrical forces between two objects.",
        "(6A) design and construct series and parallel circuits that model real-world circuits such as in-home wiring, automobile wiring, and simple electrical devices to evaluate the transfer of electrical energy;","(6B) design, evaluate, and refine a device that generates electrical energy through the interaction of electric charges and magnetic fields;","(6C) plan and conduct an investigation to provide evidence that energy is conserved within a closed system;","(6D) investigate and demonstrate the movement of thermal energy through solids, liquids, and gases by convection, conduction, and radiation such as weather, living, and mechanical systems;","(6E) plan and conduct an investigation to evaluate the transfer of energy or information through different materials by different types of waves such as wireless signals, ultraviolet radiation, and microwaves;","(6F) construct and communicate an evidence-based explanation for how wave interference, reflection, and refraction are used in technology such as medicine, communication, and scientific research; and","(6G) evaluate evidence from multiple sources to critique the advantages and disadvantages of various renewable and nonrenewable energy sources and their impact on society and the environment.",
        "(7A) model basic atomic structure and relate an element's atomic structure to its bonding, reactivity, and placement on the Periodic Table;","(7B) use patterns within the Periodic Table to predict the relative physical and chemical properties of elements;","(7C) explain how physical and chemical properties of substances are related to their usage in everyday life such as in sunscreen, cookware, industrial applications, and fuels;","(7D) explain how electrons can transition from a high energy level to a low energy state, emitting photons at different frequencies for different energy transitions;","(7E) explain how atomic energy levels and emission spectra present evidence for the wave particle duality; and","(7F) plan and conduct an investigation to provide evidence that the rate of reaction or dissolving is affected by multiple factors such as particle size, stirring, temperature, and concentration.",
        "(8A) investigate how changes in properties are indicative of chemical reactions such as hydrochloric acid with a metal, oxidation of metal, combustion, and neutralizing an acid with a base;","(8B) develop and use models to balance chemical equations and support the claim that atoms, and therefore mass, are conserved during a chemical reaction;","(8C) research and communicate the uses, advantages, and disadvantages of nuclear reactions in current technologies; and","(8D) construct and communicate an evidence-based explanation of the environmental impact of the end-products of chemical reactions such as those that may result in degradation of water, soil, air quality, and global climate change."
      ],
      'Physics': [
        "(1A) ask questions and define problems based on observations or information from text, phenomena, models, or investigations;","(1B) apply scientific practices to plan and conduct descriptive, comparative, and experimental investigations, and use engineering practices to design solutions to problems;","(1C) use appropriate safety equipment and practices during laboratory, classroom, and field investigations as outlined in Texas Education Agency-approved safety standards;","(1D) use appropriate tools such as balances, ballistic carts or equivalent, batteries, computers, constant velocity cars, convex lenses, copper wire, discharge tubes with power supply (H, He, Ne, Ar), data acquisition probes and software, dynamics and force demonstration equipment, electrostatic generators, electrostatic kits, friction blocks, graph paper, graphing technology, hand-held visual spectroscopes, inclined planes, iron filings, lab masses, laser pointers, magnets, magnetic compasses, metric rulers, motion detectors, multimeters (current, voltage, resistance), optics bench, optics kit, photogates, plane mirrors, prisms, protractors, pulleys, resistors, rope or string, scientific calculators, stopwatches, springs, spring scales, switches, tuning forks, wave generators, or other equipment and materials that will produce the same results;","(1E) collect quantitative data using the International System of Units (SI) and qualitative data as evidence;","(1F) organize quantitative and qualitative data using bar charts, line graphs, scatter plots, data tables, labeled diagrams, and conceptual mathematical relationships;","(1G) develop and use models to represent phenomena, systems, processes, or solutions to engineering problems; and","(1H) distinguish among scientific hypotheses, theories, and laws.",
        "(2A) identify advantages and limitations of models such as their size, scale, properties, and materials;","(2B) analyze data by identifying significant statistical features, patterns, sources of error, and limitations;","(2C) use mathematical calculations to assess quantitative relationships in data; and","(2D) evaluate experimental and engineering designs.",
        "(3A) develop explanations and propose solutions supported by data and models and consistent with scientific ideas, principles, and theories;",
        "(3B) communicate explanations and solutions individually and collaboratively in a variety of settings and formats; and",
        "(3C) engage respectfully in scientific argumentation using applied scientific explanations and empirical evidence.",
        "(4A) analyze, evaluate, and critique scientific explanations and solutions by using empirical evidence, logical reasoning, and experimental and observational testing, so as to encourage critical thinking by the student;","(4B) relate the impact of past and current research on scientific thought and society, including research methodology, cost-benefit analysis, and contributions of diverse scientists as related to the content; and","(4C) research and explore resources such as museums, libraries, professional organizations, private companies, online platforms, and mentors employed in a science, technology, engineering, and mathematics (STEM) field in order to investigate STEM careers.",
        "(5A) analyze different types of motion by generating and interpreting position versus time, velocity versus time, and acceleration versus time using hand graphing and real-time technology such as motion detectors, photogates, or digital applications;","(5B) define scalar and vector quantities related to one- and two-dimensional motion and combine vectors using both graphical vector addition and the Pythagorean theorem;","(5C) describe and analyze motion in one dimension using equations with the concepts of distance, displacement, speed, velocity, frames of reference, and acceleration;","(5D) describe and analyze acceleration in uniform circular and horizontal projectile motion in two dimensions using equations;","(5E) explain and apply the concepts of equilibrium and inertia as represented by Newton's first law of motion using relevant real-world examples such as rockets, satellites, and automobile safety devices;","(5F) calculate the effect of forces on objects, including tension, friction, normal, gravity, centripetal, and applied forces, using free body diagrams and the relationship between force and acceleration as represented by Newton's second law of motion;","(5G) illustrate and analyze the simultaneous forces between two objects as represented in Newton's third law of motion using free body diagrams and in an experimental design scenario; and","(5H) describe and calculate, using scientific notation, how the magnitude of force between two objects depends on their masses and the distance between their centers, and predict the effects on objects in linear and orbiting systems using Newton's law of universal gravitation.",
        "(6A) use scientific notation and predict how the magnitude of the electric force between two objects depends on their charges and the distance between their centers using Coulomb's law;","(6B) identify and describe examples of electric and magnetic forces and fields in everyday life such as generators, motors, and transformers;","(6C) investigate and describe conservation of charge during the processes of induction, conduction, and polarization using different materials such as electroscopes, balloons, rods, fur, silk, and Van de Graaf generators;","(6D) analyze, design, and construct series and parallel circuits using schematics and materials such as switches, wires, resistors, lightbulbs, batteries, voltmeters, and ammeters; and","(6E) calculate current through, potential difference across, resistance of, and power used by electric circuit elements connected in both series and parallel circuits using Ohm's law.",
        "(7A) calculate and explain work and power in one dimension and identify when work is and is not being done by or on a system;","(7B) investigate and calculate mechanical, kinetic, and potential energy of a system;","(7C) apply the concept of conservation of energy using the work-energy theorem, energy diagrams, and energy transformation equations, including transformations between kinetic, potential, and thermal energy;","(7D) calculate and describe the impulse and momentum of objects in physical systems such as automobile safety features, athletics, and rockets; and","(7E) analyze the conservation of momentum qualitatively in inelastic and elastic collisions in one dimension using models, diagrams, and simulations.",
        "(8A) examine and describe simple harmonic motion such as masses on springs and pendulums and wave energy propagation in various types of media such as surface waves on a body of water and pulses in ropes;","(8B) compare the characteristics of transverse and longitudinal waves, including electromagnetic and sound waves;","(8C) investigate and analyze characteristics of waves, including velocity, frequency, amplitude, and wavelength, and calculate using the relationships between wave speed, frequency, and wavelength;","(8D) investigate behaviors of waves, including reflection, refraction, diffraction, interference, standing wave, the Doppler effect and polarization and superposition;","(8E) compare the different applications of the electromagnetic spectrum, including radio telescopes, microwaves, and x-rays;","(8F) investigate the emission spectra produced by various atoms and explain the relationship to the electromagnetic spectrum; and","(8G) describe and predict image formation as a consequence of reflection from a plane mirror and refraction through a thin convex lens.",
        "(9A) describe the photoelectric effect and emission spectra produced by various atoms and how both are explained by the photon model for light;","(9B) investigate Malus's Law and describe examples of applications of wave polarization, including 3-D movie glasses and LCD computer screens;","(9C) compare and explain how superposition of quantum states is related to the wave-particle duality nature of light; and","(9D) give examples of applications of quantum phenomena, including the Heisenberg uncertainty principle, quantum computing, and cybersecurity."
      ],
      'Astronomy': [
        "(1A) ask questions and define problems based on observations or information from text, phenomena, models, or investigations;","(1B) apply scientific practices to plan and conduct descriptive, comparative, and experimental investigations and use engineering practices to design solutions to problems;","(1C) use appropriate safety equipment and practices during laboratory, classroom, and field investigations as outlined in Texas Education Agency-approved safety standards;","(1D) use appropriate tools such as gnomons; sundials; Planisphere; star charts; globe of the Earth; diffraction gratings; spectroscopes; color filters; lenses of multiple focal lengths; concave, plane, and convex mirrors; binoculars; telescopes; celestial sphere; online astronomical databases; and online access to observatories;","(1E) collect quantitative data using the International System of Units (SI) and qualitative data as evidence;","(1F) organize quantitative and qualitative data using graphs, charts, spreadsheets, and computer software;","(1G) develop and use models to represent phenomena, systems, processes, or solutions to engineering problems;","(1H) distinguish between scientific hypotheses, theories, and laws.",
        "(2A) identify advantages and limitations of models such as their size, scale, properties, and materials;","(2B) analyze data by identifying significant statistical features, patterns, sources of error, and limitations;","(2C) use mathematical calculations to assess quantitative relationships in data;","(2D) evaluate experimental and engineering designs.",
        "(3A) develop explanations and propose solutions supported by data and models consistent with scientific ideas, principles, and theories;","(3B) communicate explanations and solutions individually and collaboratively in a variety of settings and formats;","(3C) engage respectfully in scientific argumentation using applied scientific explanations and empirical evidence.",
        "(4A) analyze, evaluate, and critique scientific explanations and solutions by using empirical evidence, logical reasoning, and experimental and observational testing, so as to encourage critical thinking by the student;","(4B) relate the impact of past and current research on scientific thought and society, including research methodology, cost-benefit analysis, and contributions of diverse scientists as related to the content;","(4C) research and explore resources such as museums, planetariums, observatories, libraries, professional organizations, private companies, online platforms, and mentors employed in a science, technology, engineering, and mathematics (STEM) field in order to investigate STEM careers;",
        "(5A) evaluate and communicate how ancient civilizations developed models of the universe using astronomical structures, instruments, and tools such as the astrolabe, gnomons, and charts and how those models influenced society, time keeping, and navigation;","(5B) research and evaluate the contributions of scientists, including Ptolemy, Copernicus, Tycho Brahe, Kepler, Galileo, and Newton, as astronomy progressed from a geocentric model to a heliocentric model;","(5C) describe and explain the historical origins of the perceived patterns of constellations and the role of constellations in ancient and modern navigation;",
        "(6A) observe, record, and analyze the apparent movement of the Sun, Moon, and stars and predict sunrise and sunset;","(6B) observe the movement of planets throughout the year and measure how their positions change relative to the constellations;","(6C) identify constellations such as Ursa Major, Ursa Minor, Orion, Cassiopeia, and constellations along the ecliptic and describe their importance;","(6D) understand the difference between astronomy and astrology, the reasons for their historical conflation, and their eventual separation.",
        "(7A) demonstrate the use of units of measurement in astronomy, including astronomical units and light years, minutes, and seconds;","(7B) model the scale, size, and distances of the Sun, Earth, and Moon system and identify the limitations of physical models; and","(7C) model the scale, sizes, and distances of the Sun and the planets in our solar system and identify the limitations of physical models.",
        "(8A) model how the orbit and relative position of the Moon cause lunar phases and predict the timing of moonrise and moonset during each phase;","(8B) model how the orbit and relative position of the Moon cause lunar and solar eclipses; and","(8C) examine and investigate the dynamics of tides using the Sun, Earth, and Moon model.",
        "(9A) examine the relationship of a planet's axial tilt to its potential seasons;","(9B) predict how changing latitudinal position affects the length of day and night throughout a planet's orbital year;","(9C) investigate the relationship between a planet's axial tilt, angle of incidence of sunlight, and concentration of solar energy; and","(9D) explain the significance of Earth's solstices and equinoxes.",
        "(10A) investigate the use of black body radiation curves and emission, absorption, and continuous spectra in the identification and classification of celestial objects;","(10B) calculate the relative light-gathering power of different-sized telescopes to compare telescopes for different applications;","(10C) analyze the importance and limitations of optical, infrared, and radio telescopes, gravitational wave detectors, and other ground-based technology; and","(10D) analyze the importance and limitations of space telescopes in the collection of astronomical data across the electromagnetic spectrum.",
        "(11A) relate Newton's law of universal gravitation and Kepler's laws of planetary motion to the formation and motion of the planets and their satellites;","(11B) explore and communicate the origins and significance of planets, planetary rings, satellites, asteroids, comets, Oort cloud, and Kuiper belt objects;","(11C) compare the planets in terms of orbit, size, composition, rotation, atmosphere, natural satellites, magnetic fields, and geological activity; and","(11D) compare the factors essential to life on Earth such as temperature, water, gases, and gravitational and magnetic fields to conditions on other planets and their satellites.",
        "(12A) identify the approximate mass, size, motion, temperature, structure, and composition of the Sun;","(12B) distinguish between nuclear fusion and nuclear fission and identify the source of energy within the Sun as nuclear fusion of hydrogen to helium;","(12C) describe the eleven-year solar cycle and the significance of sunspots; and","(12D) analyze the origins and effects of space weather, including the solar wind, coronal mass ejections, prominences, flares, and sunspots.",
        "(13A) identify the characteristics of main sequence stars, including surface temperature, age, relative size, and composition;","(13B) describe and communicate star formation from nebulae to protostars to the development of main sequence stars;","(13C) evaluate the relationship between mass and fusion on stellar evolution;","(13D) compare how the mass of a main sequence star will determine its end state as a white dwarf, neutron star, or black hole;","(13E) describe the use of spectroscopy in obtaining physical data on celestial objects such as temperature, chemical composition, and relative motion;","(13F) use the Hertzsprung-Russell diagram to classify stars and plot and examine the life cycle of stars from birth to death;","(13G) illustrate how astronomers use geometric parallax to determine stellar distances and intrinsic luminosities; and","(13H) describe how stellar distances are determined by comparing apparent brightness and intrinsic luminosity when using spectroscopic parallax and the Leavitt relation for variable stars.",
        "(14A) illustrate the structure and components of our Milky Way galaxy and model the size, location, and movement of our solar system within it;","(14B) compare spiral, elliptical, irregular, dwarf, and active galaxies;","(14C) develop and use models to explain how galactic evolution occurs through mergers and collisions;","(14D) describe the Local Group and its relation to larger-scale structures in the universe; and","(14E) evaluate the indirect evidence for the existence of dark matter.",
        "(15A) describe and evaluate the historical development of evidence supporting the Big Bang Theory;","(15B) evaluate the limits of observational astronomy methods used to formulate the distance ladder;","(15C) evaluate the indirect evidence for the existence of dark energy;","(15D) describe the current scientific understanding of the evolution of the universe, including estimates for the age of the universe; and","(15E) describe current scientific hypotheses about the fate of the universe, including open and closed universes.",
        "(16A) describe and communicate the historical development of human space flight and its challenges;","(16B) describe and communicate the uses and challenges of robotic space flight;","(16C) evaluate the evidence of the existence of habitable zones and potentially habitable planetary bodies in extrasolar planetary systems;","(16D) evaluate the impact on astronomy from light pollution, radio interference, and space debris;","(16E) examine and describe current developments and discoveries in astronomy; and","(16F) explore and explain careers that involve astronomy, space exploration, and the technologies developed through them.",
      ],

      
    };
    
    const handleGradeLevelChange = (event) => {
    const value = event.target.value;
    setGradeLevel(value);
    setSubject('');
    setKnowledge('');
    setSkill('');
    };
    
    const handleSubjectChange = (event) => {
    const value = event.target.value;
    setSubject(value);
    setKnowledge('');
    setSkill('');
    };
    
    const handleKnowledgeChange = (event) => {
    const value = event.target.value;
    setKnowledge(value);
    setSkill('');
    };
    
    const handleSkillChange = (event) => {
    const value = event.target.value;
    setSkill(value);
    };
    
    const handleSubmit = (event) => {
    event.preventDefault();
    const values = {
    gradeLevel,
    subject,
    knowledge,
    skill,
    };
    onSubmit(values);
    };
    
    return (
    <form className="mt-10 mb-6 px-2" onSubmit={handleSubmit}>
      <div className="mb-2">
        <label htmlFor="gradeLevel">Grade Level:</label>
        <select id="gradeLevel" value={gradeLevel} onChange={handleGradeLevelChange}>
          <option value="">Select a grade level</option>
          {/*<option value="Elementary">Elementary</option>*/}
          {/*<option value="Middle School">Middle School</option>*/}
          <option value="High School">High School</option>
        </select>
        </div>
        {gradeLevel && (
        <div className="mb-2">
        <label htmlFor="subject">Subject:</label>
        <select id="subject" value={subject} onChange={handleSubjectChange}>
          <option value="">Select a subject</option>
          {subjectOptions[gradeLevel].map((option) => (
          <option key={option} value={option}>
          {option}
          </option>
        ))}
        </select>
        </div>
        )}
        {subject && (
        <div className="mb-2">
        <label htmlFor="knowledge">Knowledge:</label>
        <select id="knowledge" value={knowledge} onChange={handleKnowledgeChange}>
          <option value="">Select a knowledge</option>
          {knowledgeOptions[subject].map((option) => (
          <option key={option} value={option}>
          {option}
          </option>
        ))}
        </select>
        </div>
        )}
        {knowledge && (
        <div className="w-fit">
        <label htmlFor="skill">Skill:</label>
        <select id="skill" className="w-96 truncate" value={skill} onChange={handleSkillChange}>
          <option className="w-28" value="">Select a skill</option>
          {skillOptions[knowledge].map((option) => (
          <option className="w-28" key={option} value={option}>
          {option}
          </option>
        ))}
        </select>
        </div>
        )}
        {skill && (
        <div className="mt-2">
        <button className="mt-6 w-28 h-10 bg-slate-300 border text-l hover:bg-slate-500" type="submit">Submit</button>
      </div>
      )}
    </form>
    );
    };
    
    export default Form;
    
    
    
    